lib LibFreetype
  FT_FSTYPE_XXX = {
    "FT_FSTYPE_INSTALLABLE_EMBEDDING"        => 0x0000,
    "FT_FSTYPE_RESTRICTED_LICENSE_EMBEDDING" => 0x0002,
    "FT_FSTYPE_PREVIEW_AND_PRINT_EMBEDDING"  => 0x0004,
    "FT_FSTYPE_EDITABLE_EMBEDDING"           => 0x0008,
    "FT_FSTYPE_NO_SUBSETTING"                => 0x0100,
    "FT_FSTYPE_BITMAP_EMBEDDING_ONLY"        => 0x0200,
  }
end
