lib LibFreetype
  FT_KERNING_DEFAULT  = 0
  FT_KERNING_UNFITTED = 1
  FT_KERNING_UNSCALED = 2

  enum FT_Kerning_Mode
    DEFAULT  = FT_KERNING_DEFAULT
    UNFITTED = FT_KERNING_UNFITTED
    UNSCALED = FT_KERNING_UNSCALED
  end
end
