lib LibFreetype
  FT_PIXEL_MODE_NONE  = 0
  FT_PIXEL_MODE_MONO  = 1
  FT_PIXEL_MODE_GRAY  = 2
  FT_PIXEL_MODE_GRAY2 = 3
  FT_PIXEL_MODE_GRAY4 = 4
  FT_PIXEL_MODE_LCD   = 5
  FT_PIXEL_MODE_LCD_V = 6
  FT_PIXEL_MODE_MAX   = 7
  FT_PIXEL_MODE_BGRA  = 8

  enum FT_Pixel_Mode
    NONE  = FT_PIXEL_MODE_NONE
    MONO  = FT_PIXEL_MODE_MONO
    GRAY  = FT_PIXEL_MODE_GRAY
    GRAY2 = FT_PIXEL_MODE_GRAY2
    GRAY4 = FT_PIXEL_MODE_GRAY4
    LCD   = FT_PIXEL_MODE_LCD
    LCD_V = FT_PIXEL_MODE_LCD_V
    BGRA  = FT_PIXEL_MODE_BGRA
    MAX   = FT_PIXEL_MODE_MAX
  end
end
