lib LibFreetype
  FT_RENDER_MODE_NORMAL = 0
  FT_RENDER_MODE_LIGHT  = 1
  FT_RENDER_MODE_MONO   = 2
  FT_RENDER_MODE_LCD    = 3
  FT_RENDER_MODE_LCD_V  = 4

  FT_RENDER_MODE_MAX = 5

  enum FT_Render_Mode
    NORMAL = FT_RENDER_MODE_NORMAL
    LIGHT  = FT_RENDER_MODE_LIGHT
    MONO   = FT_RENDER_MODE_MONO
    LCD    = FT_RENDER_MODE_LCD
    LCD_V  = FT_RENDER_MODE_LCD_V
    MAX    = FT_RENDER_MODE_MAX
  end
end
