lib LibFreetype
  FT_SIZE_REQUEST_TYPE_NOMINAL  = 0
  FT_SIZE_REQUEST_TYPE_REAL_DIM = 1
  FT_SIZE_REQUEST_TYPE_BBOX     = 2
  FT_SIZE_REQUEST_TYPE_CELL     = 3
  FT_SIZE_REQUEST_TYPE_SCALES   = 4

  FT_SIZE_REQUEST_TYPE_MAX = 5

  enum FT_Size_Request_Type
    NOMINAL  = FT_SIZE_REQUEST_TYPE_NOMINAL
    REAL_DIM = FT_SIZE_REQUEST_TYPE_REAL_DIM
    BBOX     = FT_SIZE_REQUEST_TYPE_BBOX
    CELL     = FT_SIZE_REQUEST_TYPE_CELL
    SCALES   = FT_SIZE_REQUEST_TYPE_SCALES
    MAX      = FT_SIZE_REQUEST_TYPE_MAX
  end
end
