lib LibFreetype
  FT_STROKER_LINECAP_BUTT   = 0
  FT_STROKER_LINECAP_ROUND  = 1
  FT_STROKER_LINECAP_SQUARE = 2

  enum FT_Stroker_LineCap
    BUTT   = FT_STROKER_LINECAP_BUTT
    ROUND  = FT_STROKER_LINECAP_ROUND
    SQUARE = FT_STROKER_LINECAP_SQUARE
  end
end
